pipeline {
    agent {
        label 'jenkins-slave' // Specify the Jenkins agent where the pipeline will run
        // Specify the Maven version to use
        // You should have already configured this version in Jenkins under "Global Tool Configuration"
        tools {
            maven 'Maven-3.2.5'
        }
    }
    options {
        // Use timestamps for console output
        timestamps()
    }
    stages {
        stage('Build') {
            steps {
                // Run Maven build
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                // Run Maven test phase
                sh 'mvn test'
            }
            post {
                always {
                    // Publish JUnit test results
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                // Execute deliver.sh script
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
