pipeline {
    agent {
        label 'jenkins-slave' // Specify the Jenkins agent where the pipeline will run
    }
    stages {
        stage('Build') {
            steps {
                sh '-B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
